# Generated by Django 5.1.2 on 2024-10-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date_created', models.DateField(verbose_name='date created')),
                ('last_login', models.DateTimeField(verbose_name='last login')),
            ],
        ),
    ]
